### ISSUE TITLE
brew upgrade php54-augmentedtypes fails on missing phpdoc

### ISSUE THREAD

**Issue by silvamerica** [box/augmented_types#14]
It looks like attempting to install php54 (a dependency for php54-augmentedtypes) breaks on a missing phpdoc.

```
mbp:~ $ brew upgrade php54-augmentedtypes
==> Upgrading 1 outdated package, with result:
php54-augmentedtypes 0.6.2
==> Upgrading php54-augmentedtypes
==> Installing php54-augmentedtypes dependency: php54
==> Downloading http://www.php.net/get/php-5.4.30.tar.bz2/from/this/mirror
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php54/5.4.30 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.4 --with-config-file-path=/usr/local/e
==> make
==> make install
==> /usr/local/Cellar/php54/5.4.30/bin/pear config-set php_ini /usr/local/etc/php/5.4/php.ini
 in Unknown on line 0

Fatal error: Function annotation compilation failed for function usage in file /usr/local/Cellar/php54/5.4.30/lib/php/pearcmd.php at line 318, error message: No phpdoc specified - all named functions require phpdoc. (Did you remember to use /** ?)
 in Unknown on line 0


READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
Error: undefined local variable or method `f' for #<BuildError:0x007f9e22837378>
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Homebrew/exceptions.rb:182:in `dump'
/usr/local/Library/Homebrew/cmd/upgrade.rb:84:in `rescue in upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:92:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:43:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:43:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:43:in `upgrade'
/usr/local/Library/brew.rb:131:in `<main>'
```

**Comment by jmarrama** [comment]
@jhuffaker  - you hit a recent problem right on the head. Nasty stuff happens when files are ran before the whitelist and blacklist can be processed. I just added functionality to add paths to the white/blacklist via two ini directives 'whitelist' and 'blacklist' in commit https://github.com/box/augmented_types/commit/eed4bdf1e9bdfb3aaa84b79264ec8e48e863cd20
